# Generated by Django 4.1.1 on 2022-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1', models.CharField(default='', max_length=70)),
                ('Team2', models.CharField(default='', max_length=60)),
                ('Venue', models.CharField(default='', max_length=100)),
                ('Date', models.DateField()),
                ('Adult', models.CharField(default='', max_length=50)),
                ('Children', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1', models.CharField(default='', max_length=70)),
                ('Team2', models.CharField(default='', max_length=60)),
                ('Venue', models.CharField(default='', max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
